// Research and publications (/therapist/research, /therapist/publications).
//
// DEMO ONLY. Static snapshot of metiv.org (scraped 2026-09-13). Bibliographic
// data is copied as listed on metiv.org (including its gaps: many entries have
// no year, volume or link). Nothing was looked up elsewhere. Study summaries are
// neutral; "breakthrough"/"expected to be effective" wording was removed.

/**
 * @typedef {{ name?: string, role?: string, email?: string, whatsapp?: string }} Contact
 *
 * @typedef {{
 *   slug: string,
 *   title: string,
 *   summary: string,
 *   description: string,
 *   population: string,
 *   status: string,
 *   recruiting: boolean,
 *   eligibility?: string[],
 *   team?: string[],
 *   links?: { label: string, url: string }[],
 *   contact?: Contact,
 *   sourceUrl: string,
 * }} Study
 *
 * @typedef {{
 *   title: string,
 *   authors: string[],
 *   year?: number,
 *   publisher?: string,
 *   language: 'en'|'he',
 *   audience: 'public'|'professional',
 *   role?: string,
 *   url?: string,
 *   sourceUrl: string,
 * }} Book
 *
 * @typedef {'veterans'|'children-family'|'adolescents'|'schools-resilience'|'growth'|'terror-war'|'treatment'|'policy'|'other'} PaperTopic
 *
 * type: 'article' for journal papers, 'chapter' for book chapters/entries
 * (then `journal` holds the book title). `details` holds volume/pages as listed.
 * @typedef {{
 *   title: string,
 *   authors: string[],
 *   journal: string,
 *   year?: number,
 *   details?: string,
 *   doi?: string,
 *   url?: string,
 *   language?: 'en'|'he',
 *   type: 'article'|'chapter',
 *   topic: PaperTopic,
 *   featured?: boolean,
 *   sourceUrl: string,
 * }} Paper
 */

const METIV = 'https://metiv.org';
const PAST = `${METIV}/מחקרי-עבר-ופרסומים/`;
const RECENT = `${METIV}/מאמרים-ונתונים/`;
const ACTIVE = `${METIV}/מחקרים-פעילים-טראומה/`;

export const RESEARCH_INTRO = {
  title: 'יחידת המחקר של מטיב',
  paragraphs: [
    'יחידת המחקר אחראית על ידע יישומי ומדעי, הערכת תוכניות טיפול ושיטות טיפול, הערכת הכשרות למטפלים, פיתוח כלים ואיסוף נתונים לטובת קבלת החלטות.',
    'בנוסף, העבודה הטיפולית במטיב נמצאת תחת בקרה מתמדת, ונבחנת בעזרת כלים אבחוניים על מנת לבדוק ולעקוב אחר הקשיים וההתקדמות של המטופלים.',
  ],
  focus: 'טיפול בפוסט טראומה בקרב אוכלוסיות יעד אזרחיות וצבאיות.',
  role: 'גישור בין ידע מחקרי לבין העשייה הטיפולית בשטח; תרגום תובנות לנהלים ולפרקטיקות; תמיכה בגיוס משאבים.',
  principles: ['רלוונטיות קלינית', 'תקפות מדעית', 'אתיקה והגנת פרטיות', 'שקיפות והפצת ידע', 'שותפות עם מטפלים וקהילות יעד'],
  pastResearchAreas: [
    'חוסן בילדים ובני נוער בישראל',
    'הבנת המורכבות של חוויותיהם של לוחמים משוחררים',
    'פיתוח ובחינת שיטות התערבות וטיפול עבור אוכלוסיות שונות',
    'מחקר בנושא טיפול בעזרת SE (Somatic Experiencing) בהפרעת דחק פוסט טראומטית (PTSD)',
  ],
  collaborationContact: { name: 'שיר אליאס', role: 'מנהלת המחקר', email: 'shir@metiv.org' },
  journalClub: {
    title: `ג'ורנל קלאב`,
    description: 'קהילה לומדת על מחקר וטיפול בטראומה, ללא עלות.',
    url: 'https://youtube.com/playlist?list=PL7kR2brVa2aHQOHC1realKQBf6950Yip1',
  },
  booksOrderingNote: 'למידע על הזמנת הספרים בישראל: info@metiv.org',
  sourceUrl: ACTIVE,
};

/** @type {Study[]} */
export const ACTIVE_STUDIES = [
  {
    slug: 'release-journey-study',
    title: 'מחקר מסע שחרור',
    summary: 'מחקר הערכה ומדידה שמלווה את תכניות מסע שחרור לחיילים משוחררים.',
    description: 'מחקר מסע שחרור - ליווי תכניות מסע שחרור, מחקר הערכה ומדידה של התכניות השונות.',
    population: 'חיילים משוחררים המשתתפים בתכניות מסע שחרור',
    status: 'פעיל',
    recruiting: false,
    sourceUrl: ACTIVE,
  },
  {
    slug: 'mdma-sea-it',
    title: 'מחקר MDMA / SEA-IT',
    summary: 'מחקר קליני המשווה בין שני טיפולים אינטנסיביים ל-PTSD על רקע צבאי: תרפיה הנתמכת ב-MDMA ו-SEA-IT.',
    description: `חיילים משוחררים רבים סובלים מסימפטומים של PTSD יחד עם קשיים פסיכולוגיים נוספים, הקשורים לחוויות שעברו או היו עדים להן במהלך שירותם הצבאי.

המחקר הנוכחי מציע שני טיפולים אינטנסיביים:

- **טיפול אחד** הוא תרפיה הנתמכת ב-MDMA, המשלבת צריכה של החומר הפסיכדלי ומלווה בפסיכותרפיה מותאמת.
- **הטיפול השני** הוא SEA-IT (Somatic Experiential Acceptance Intensive Trauma focused Therapy), תרפיה אינטנסיבית ממוקדת גוף, חוויה וקבלה במודל פסיכדלי.

במחקר מבקשים לבחון את האופנים שבהם הטיפולים משפיעים על אספקטים פסיכולוגיים ונוירו-פסיכולוגיים שונים, ולהבין את המכניזם של הטיפול האינטנסיבי.

ההתאמה למחקר היא על בסיס תהליך אבחון ולא מאפשרת בחירה בין הטיפולים.`,
    population: 'מתמודדים עם PTSD על רקע צבאי, שהיו בטיפול ממוקד טראומה קודם והתסמינים נמשכים',
    status: 'גיוס משתתפים',
    recruiting: true,
    eligibility: [
      'מתמודד עם טראומה צבאית או PTSD',
      'השתתף בעבר בטיפול ממוקד טראומה אך התסמינים נמשכים',
      'מסוגל להתחייב לתהליך אינטנסיבי של 3-3.5 חודשים (16 מפגשים, בירושלים)',
    ],
    team: [`ד"ר אנה הרווד גרוס`, 'דליה עמית זיוון', `ד"ר עמיחי פלור`, `בפיקוח פרופ' פנחס דנון, ראש פסיכיאטריה בית החולים הרצוג`],
    links: [
      { label: 'שאלון התאמה', url: 'https://www.surveyhero.com/c/jzkapqr4' },
      { label: 'מכתב הסבר על SEA-IT (PDF)', url: `${METIV}/wp-content/uploads/2025/07/מכתב-הסבר-SEA-IT.pdf` },
      { label: 'כתבה בעיתון מקור ראשון (PDF)', url: `${METIV}/wp-content/uploads/2025/07/MAKOR-RISHON-ARTICLE.pdf` },
    ],
    contact: { email: 'moriya@metiv.org', whatsapp: '026264889' },
    sourceUrl: `${METIV}/sea-it-mdma/`,
  },
  {
    slug: 'clinics-study',
    title: 'מחקר מרפאות',
    summary: 'מחקר על תוספת טיפולים משלימים לפסיכותרפיה בפוסט טראומה צבאית.',
    description: 'תוספות טיפולים משלימים לפסיכותרפיה בפוסט טראומה צבאית.',
    population: 'מטופלים עם פוסט טראומה צבאית',
    status: 'פעיל',
    recruiting: false,
    contact: { name: `ד"ר אנה פורטוגלוב`, role: 'אחראית מחקר מרפאות' },
    sourceUrl: ACTIVE,
  },
  {
    slug: 'se-pe',
    title: 'מחקר SE PE',
    summary: 'מחקר השוואתי בין החוויה הסומטית (SE) לחשיפה ממושכת (PE) בטיפול בפוסט טראומה צבאית, הניתן ללא עלות ברחבי הארץ.',
    description: `מחקר השוואתי בין שתי שיטות טיפול לפוסט טראומה: החוויה הסומטית (SE) בהשוואה לחשיפה ממושכת (PE). המחקר התקיים בתקופות שונות - קורונה, הפוגה ומלחמה - ונותן תמונה רחבה על התמודדות עם פוסט טראומה בישראל במציאות משתנה.

במסגרת המערך ניתן טיפול ללא עלות, בכל הארץ, למתמודדים עם PTSD מהשירות הצבאי (רק לחיילים משוחררים, שאינם בסדיר). הטיפול ניתן באחת משתי השיטות על ידי מטפלים מוסמכים, ומלווה במילוי שאלונים, הערכות קליניות וליווי של מטיב. הנתונים משמשים למחקר קליני.`,
    population: 'חיילים משוחררים (לא בשירות סדיר) המתמודדים עם PTSD מהשירות הצבאי',
    status: 'פעיל',
    recruiting: true,
    contact: { email: 'shir@metiv.org', whatsapp: '02-5952240' },
    sourceUrl: ACTIVE,
  },
  {
    slug: 'reservists-with-ptsd',
    title: 'מחקר לוחמים עם PTSD',
    summary: 'מחקר איכותני על החוויה של חזרה ללחימה במלחמת חרבות ברזל אצל לוחמים שהתמודדו עם פוסט טראומה צבאית עוד לפני המלחמה.',
    description: `מחקר איכותני: ניתוח ראיונות עם לוחמים שגויסו למילואים עם רקע של התמודדות עם PTSD. מחקר אורך בתקופת מלחמת חרבות ברזל.

במסגרת המחקר מתקיים ראיון פתוח עם לוחמים שהשתתפו במלחמה, בניסיון להבין את הסיפור, את המורכבות ואת ההתמודדות.`,
    population: 'לוחמי מילואים שהתמודדו עם פוסט טראומה צבאית לפני מלחמת חרבות ברזל',
    status: 'פעיל',
    recruiting: true,
    contact: { email: 'shir@metiv.org', whatsapp: '02-5952240' },
    sourceUrl: ACTIVE,
  },
  {
    slug: 'kids-department-study',
    title: 'מחקר מחלקת ילדים',
    summary: 'מעקב אחר תוכניות ההתערבות של מחלקת הילדים: טיפולים לילדים ומשפחות, טיפולים דיאדיים ותוכניות בבתי ספר.',
    description: 'מעקב אחרי תוכניות התערבות, מחקר טיפולים לפוסט טראומה לילדים ומשפחות, טיפולים דיאדיים ותוכניות התערבות בבתי ספר.',
    population: 'ילדים ומשפחות',
    status: 'פעיל',
    recruiting: false,
    sourceUrl: ACTIVE,
  },
  {
    slug: 'ai-and-ptsd',
    title: 'מחקר פוסט טראומה ובינה מלאכותית',
    summary: 'תחום מחקר חדש במטיב המשלב בינה מלאכותית, מרקרים פיזיולוגיים וניתוחי עומק להערכה ולטיפול ב-PTSD.',
    description: 'תחום מחקר חדש במטיב: שילוב בינה מלאכותית, מרקרים פיזיולוגיים וניתוחי עומק, לטיפול והערכה של PTSD.',
    population: 'מתמודדים עם PTSD',
    status: 'פעיל',
    recruiting: false,
    sourceUrl: ACTIVE,
  },
];

/** @type {Book[]} */
export const BOOKS = [
  {
    title: 'Helping Children Cope With Trauma: Individual, Family, and Community Perspectives',
    authors: ['Ruth Pat-Horenczyk', 'Danny Brom', 'Juliet M. Vogel'],
    role: 'Edited by',
    year: 2013,
    publisher: 'Routledge',
    language: 'en',
    audience: 'professional',
    url: 'http://www.amazon.com/gp/product/0415504562/',
    sourceUrl: PAST,
  },
  {
    title: 'Treating Traumatized Children: Risk, Resilience and Recovery',
    authors: ['Danny Brom', 'Ruth Pat-Horenczyk', 'Julian Ford'],
    role: 'Edited by',
    year: 2008,
    publisher: 'Routledge',
    language: 'en',
    audience: 'professional',
    url: 'http://www.amazon.com/gp/product/B001OLRO08/',
    sourceUrl: PAST,
  },
  {
    title: 'The Trauma of Terrorism: Sharing Knowledge and Shared Care: An International Handbook',
    authors: ['Yael Danieli', 'Danny Brom', 'Joe Sills'],
    role: 'Edited by',
    year: 2005,
    publisher: 'Routledge',
    language: 'en',
    audience: 'professional',
    url: 'http://www.amazon.com/gp/product/0789027739/',
    sourceUrl: PAST,
  },
  {
    title: 'Coping with Trauma: Theory, Prevention and Treatment',
    authors: ['Rolf J. Kleber', 'Danny Brom', 'Peter B. Defares'],
    role: 'By',
    year: 2003,
    publisher: 'Routledge',
    language: 'en',
    audience: 'professional',
    url: 'http://www.amazon.com/gp/product/B00ZLVJDII/',
    sourceUrl: PAST,
  },
];

/** Hebrew labels for PAPER topic filter chips. */
export const PAPER_TOPICS = {
  veterans: 'לוחמים, מילואים וחיילים משוחררים',
  'children-family': 'ילדים ומשפחות',
  adolescents: 'מתבגרים',
  'schools-resilience': 'חוסן ובתי ספר',
  growth: 'צמיחה פוסט-טראומטית',
  'terror-war': 'טרור ומלחמה',
  treatment: 'שיטות טיפול',
  policy: 'מדיניות ומימון',
  other: 'אחר',
};

/** @type {Paper[]} */
export const PAPERS = [
  // ── Recent (מאמרים ונתונים, מחקרים פעילים באנגלית) ──
  {
    title: 'A nation at (ongoing) war: The effect of societal and forward-focused coping on symptoms of continuous traumatic stress',
    authors: ['Harwood-Gross, A.', 'Stern, N.', 'Lambez, B.', 'Aloni, R.'],
    journal: 'Psychological Trauma: Theory, Research, Practice, and Policy',
    year: 2025,
    details: 'Online First Publication, May 5, 2025',
    doi: '10.1037/tra0001934',
    url: 'https://psycnet.apa.org/doiLanding?doi=10.1037%2Ftra0001934',
    type: 'article',
    topic: 'terror-war',
    featured: true,
    sourceUrl: `${METIV}/en/current-research/`,
  },
  {
    title: 'The effect of MDMA administration on oxytocin concentration levels: systematic review and a multilevel meta-analysis in humans',
    authors: ['Anna Vaslavski', 'Anna Harwood Gross', 'Salomon Israel', 'Leehe Peled-Avron'],
    journal: 'Neuroscience and Biobehavioral Reviews',
    year: 2025,
    details: '177',
    url: `${METIV}/wp-content/uploads/2026/01/The-effect-of-MDMA-administration-on-oxytocin-concentration-levels.pdf`,
    type: 'article',
    topic: 'treatment',
    featured: true,
    sourceUrl: RECENT,
  },
  {
    title: `It's better to run towards the fire: The experience of reserve duty for reservists with PTSD prior to re-enlistment`,
    authors: ['Anna Harwood-Gross', 'Shir Elias', 'Dalia Amit Zivan', 'Rona Davis'],
    journal: 'International Journal of Clinical and Health Psychology',
    details: '25',
    url: `${METIV}/wp-content/uploads/2026/01/Its-better-to-run-towards-the-fire.pdf`,
    type: 'article',
    topic: 'veterans',
    featured: true,
    sourceUrl: RECENT,
  },
  {
    title: `Veterans' experiences of somatic experiencing and prolonged exposure therapies for post-traumatic stress disorder: A qualitative analysis`,
    authors: ['Anna Harwood-Gross', 'Shir Elias', 'Karen Lerner', 'Nitsa Nacasch', 'Cathy Lawi', 'Danny Brom', 'Adi Barak'],
    journal: 'Psychol Psychother',
    year: 2025,
    url: `${METIV}/wp-content/uploads/2026/01/Psychol-Psychother-2025-Harwood‐Gross-Veterans-experiences-of-somatic-experiencing-and-prolonged-exposure-therapies-1.pdf`,
    type: 'article',
    topic: 'veterans',
    featured: true,
    sourceUrl: RECENT,
  },
  {
    title: 'Outside the Realm of Combat: The Relationship of Cumulative Trauma With Perceived Military Betrayal and Military-Related Posttraumatic Stress Disorder Symptoms',
    authors: ['Harwood-Gross, A.', 'Stern, N.'],
    journal: 'Traumatology',
    year: 2024,
    url: `${METIV}/wp-content/uploads/2026/01/Harwood-gross-stern-2024.pdf`,
    type: 'article',
    topic: 'veterans',
    featured: true,
    sourceUrl: RECENT,
  },
  {
    title: 'Moral Injury as a Social Phenomenon: Looking at the Unique Relationship with System Justification',
    authors: ['Anna Harwood-Gross', 'Michelle Vayngrib', 'Eran Halperin'],
    journal: 'Journal of Aggression, Maltreatment & Trauma',
    url: `${METIV}/wp-content/uploads/2026/01/Moral-Injury-as-a-Social-Phenomenon-Looking-at-the-Unique-Relationship-with-System-Justification.pdf`,
    type: 'article',
    topic: 'veterans',
    featured: true,
    sourceUrl: RECENT,
  },
  {
    title: 'Trauma care in crisis: war trauma and mental health funding',
    authors: ['Anna Harwood-Gross', 'Danny Brom', 'Sarit Schramm-Yavin', 'Eyal Fruchter', 'Eric Vermetten'],
    journal: 'European Journal of Psychotraumatology',
    url: `${METIV}/wp-content/uploads/2026/01/Trauma-care-in-crisis-war-trauma-and-mental-health-funding.pdf`,
    type: 'article',
    topic: 'policy',
    featured: true,
    sourceUrl: RECENT,
  },
  {
    title: 'Peace of mind: Promoting psychological growth and reducing the suffering of combat veterans',
    authors: ['Anna Harwood-Gross', 'Alon Weltman', 'Yaniv Kanat-Maymon', 'Ruth Pat-Horenczyk', 'Danny Brom'],
    journal: 'Military Psychology',
    year: 2022,
    url: `${METIV}/wp-content/uploads/2026/01/POM-2022.pdf`,
    type: 'article',
    topic: 'veterans',
    featured: true,
    sourceUrl: RECENT,
  },
  {
    title: 'Peace of Mind for Israeli Combat Veterans: A Pilot Study',
    authors: ['Danny Brom', 'Alon Weltman', 'Anna Harwood-Gross', 'Ruth Pat-Horenczyk'],
    journal: 'Israel Journal of Psychiatry',
    details: 'Vol. 57',
    url: `${METIV}/wp-content/uploads/2026/01/Israel-Journal-of-Psychiatry-POM-article.pdf`,
    type: 'article',
    topic: 'veterans',
    featured: true,
    sourceUrl: RECENT,
  },

  // ── Articles in journals (partial list, מחקרי עבר ופרסומים) ──
  {
    title: 'Mothers and young children under fire: Comparing exposure to ongoing terror with exposure to time-limited war',
    authors: ['Pat-Horenczyk, R.', 'Achituv, M.', 'Asulin-Peretz, L.', 'Kaminer, H.', 'Kaplanski, N.', 'Rozenblatt, O.', 'Brom, D.'],
    journal: 'Megamot',
    year: 2016,
    details: '50(2), 29-54',
    language: 'he',
    type: 'article',
    topic: 'children-family',
    sourceUrl: PAST,
  },
  {
    title: 'Stability and Transitions in Posttraumatic Growth Trajectories among Cancer Survivors: LCA and LTA Analyses',
    authors: ['Pat-Horenczyk, R.', 'Saltzman, L. Y.', 'Hamama-Raz, Y.', 'Perry, S.', 'Ziv, Y.', 'Ginat-Frolich, R.', 'Stemmer, S. M.'],
    journal: 'Psychological Trauma: Theory, Research, Practice and Policy',
    year: 2015,
    details: 'in press',
    type: 'article',
    topic: 'growth',
    sourceUrl: PAST,
  },
  {
    title: 'The Role of Cognitive Emotional Regulation in Coping with Breast Cancer; Long-term Outcome of a Group Intervention Study',
    authors: ['Hamama-Raz, Y.', 'Pat-Horenczyk, R.', 'Perry, S.', 'Ziv, Y.', 'Bar-Levav, R.', 'Stemmer, S.M.'],
    journal: 'Integrative Cancer Therapies',
    year: 2015,
    details: 'online first publication, October 2015',
    doi: '10.1177/1534735415607318',
    type: 'article',
    topic: 'growth',
    sourceUrl: PAST,
  },
  {
    title: 'Posttraumatic Growth in Breast Cancer Survivors: Constructive and Illusory Processes',
    authors: ['Pat-Horenczyk, R.', 'Perry, S.', 'Hamama-Raz, Y.', 'Ziv, Y.', 'Schramm-Yavin, S.', 'Stemmer, S.M.'],
    journal: 'Journal of Traumatic Stress',
    year: 2015,
    details: '28, 214-222',
    doi: '10.1002/jts.22014',
    type: 'article',
    topic: 'growth',
    sourceUrl: PAST,
  },
  {
    title: 'Emotion regulation in mothers and young children faced with trauma',
    authors: ['Pat-Horenczyk, R.', 'Cohen, S.', 'Ziv, Y.', 'Achituv, M.', 'Asulin-Peretz, L.', 'Blanchard, T.', 'Schiff, M.', 'Brom, D.'],
    journal: 'Infant Mental Health Journal',
    year: 2015,
    details: '36(2), 1-12',
    doi: '10.1002/imhj.21515',
    type: 'article',
    topic: 'children-family',
    sourceUrl: PAST,
  },
  {
    title: `Building Emotion and Affect Regulation (BEAR): Preliminary evidence from an open trial in children's residential group homes in Singapore`,
    authors: ['Pat-Horenczyk, R.', 'Sim Wei Shi, C.', 'Schramm-Yavin, S.', 'Bar-Halpern, M.', 'Tan, Li Jen'],
    journal: 'Child & Youth Care Forum',
    year: 2015,
    details: '44, 175-190',
    doi: '10.1007/s10566-014-9276-8',
    type: 'article',
    topic: 'children-family',
    sourceUrl: PAST,
  },
  {
    title: 'Perceived need for psychosocial services in the context of political violence: Psychological distress among Israeli mothers with young children',
    authors: ['Schiff, M.', 'Pat-Horenczyk, R.'],
    journal: 'Clinical Social Work Journal',
    year: 2014,
    details: '42, 346-356',
    doi: '10.1007/s10615-013-0471-0',
    type: 'article',
    topic: 'children-family',
    sourceUrl: PAST,
  },
  {
    title: 'Making room for play: An innovative intervention for toddlers and families under rocket fire',
    authors: ['Cohen, E.', 'Pat-Horenczyk, R.', 'Haar-Shamir, D.'],
    journal: 'Clinical Social Work Journal',
    year: 2014,
    details: '42(4), 336-345',
    doi: '10.1007/s10615-013-0439-0',
    type: 'article',
    topic: 'children-family',
    sourceUrl: PAST,
  },
  {
    title: 'Protective factors based model for screening for posttraumatic distress in adolescents',
    authors: ['Pat-Horenczyk, R.', 'Kenan, A.M.', 'Achituv, M.', 'Bachar, E.'],
    journal: 'Child and Youth Care Forum',
    year: 2014,
    details: '43(3), 339-351',
    doi: '10.1007/s10566-013-9241-y',
    type: 'article',
    topic: 'adolescents',
    sourceUrl: PAST,
  },
  {
    title: 'Relational trauma in times of political violence: Continuous traumatic stress vs. past trauma',
    authors: ['Pat-Horenczyk, R.', 'Ziv, Y.', 'Asulin-Peretz, L.', 'Achituv, M.', 'Cohen, S.', 'Brom, D.'],
    journal: 'Peace and Conflict: Journal of Peace Psychology',
    year: 2013,
    details: '19(2), 125-137',
    doi: '10.1037/a0032488',
    type: 'article',
    topic: 'terror-war',
    sourceUrl: PAST,
  },
  {
    title: 'Transitioning from the battlefield to home: An innovative program for soldiers',
    authors: ['Baum, N.', 'Brom, D.', 'Pat-Horenczyk, R.', 'Rahabi, S.', 'Wardi, J.', 'Weltmann, A.'],
    journal: 'Journal of Aggression, Maltreatment & Trauma',
    year: 2013,
    details: '22(6), 644-659',
    type: 'article',
    topic: 'veterans',
    sourceUrl: PAST,
  },
  {
    title: 'Helping children exposed to war and violence: Perspectives from an international work group on interventions for youth and families',
    authors: ['Kletter, H.', 'Rialon, R. A.', 'Laor, N.', 'Brom, D.', 'Pat-Horenczyk, R.', 'Shaheen, M.', 'Hamiel, D.', 'Chemtob, C.', 'Weems, C. F.', 'Feinstein, C.', 'Lieberman, A.', 'Reicherter, D.', 'Song, S.', 'Carrion, V. G.'],
    journal: 'Child & Youth Care Forum',
    year: 2013,
    details: '80-90',
    type: 'article',
    topic: 'children-family',
    sourceUrl: PAST,
  },
  {
    title: 'Training teachers to build resilience in children in the aftermath of war: A cluster randomized trial',
    authors: ['Baum, N.', 'Lopes Cardozo, B.', 'Pat-Horenczyk, R.', 'Ziv, Y.', 'Blanton, C.', 'Reza, A.', 'Weltman, A.', 'Brom, D.'],
    journal: 'Child and Youth Care Forum',
    year: 2013,
    type: 'article',
    topic: 'schools-resilience',
    sourceUrl: PAST,
  },
  {
    title: 'Growing up under fire: Building resilience in young children and parents exposed to ongoing missile attacks',
    authors: ['Pat-Horenczyk, R.', 'Achituv, M.', 'Kagan-Rubenstein, A.', 'Khodabakhsh, A.', 'Brom, D.', 'Chemtob, C.M.'],
    journal: 'Journal of Child & Adolescent Trauma',
    year: 2012,
    details: '5(4), 303-314',
    type: 'article',
    topic: 'children-family',
    sourceUrl: PAST,
  },
  {
    title: `High school students' posttraumatic symptoms, substance abuse and involvement in violence in the aftermath of war`,
    authors: ['Schiff, M.', 'Pat-Horenczyk, R.', 'Benbenishty, R.', 'Brom, D.', 'Baum, N.', 'Astor, R.A.'],
    journal: 'Social Science & Medicine',
    year: 2012,
    details: '75, 1321-1328',
    type: 'article',
    topic: 'adolescents',
    sourceUrl: PAST,
  },
  {
    title: 'Can there be a "rosy" future for the "Color Red" children? A program for building resilience for toddlers exposed to ongoing terrorism in Sderot',
    authors: ['Pat-Horenczyk, R.', 'Peled, O.', 'Achituv, M.', 'Brom, D.', 'Rozenblatt, O.', 'Faierman, Z.', 'Kaplansky, N.', 'Yossef, D.', 'Lahad, M.', 'Chemtob, C.M.'],
    journal: 'Society and Social Welfare',
    year: 2012,
    details: '32(2), 237-259',
    language: 'he',
    type: 'article',
    topic: 'children-family',
    sourceUrl: PAST,
  },
  {
    title: 'Factors affecting participation in group intervention in patients after adjuvant treatment for early-study breast cancer',
    authors: ['Hamama-Raz, Y.', 'Perry, S.', 'Pat-Horenczyk, R.', 'Bar-Levav, R.', 'Stemmer, S.'],
    journal: 'Acta Oncologica',
    year: 2012,
    details: '51, 208-214',
    type: 'article',
    topic: 'growth',
    sourceUrl: PAST,
  },
  {
    title: 'Coping flexibility and complicated grief: A comparison of American and Chinese samples',
    authors: ['Burton, C.', 'Yan, O.H.', 'Bonanno, G.A.', 'Pat-Horenczyk, R.', 'Chan, S.E.', 'Ho, S.'],
    journal: 'Depression and Anxiety',
    year: 2012,
    details: '29(1), 16-22',
    type: 'article',
    topic: 'other',
    sourceUrl: PAST,
  },
  {
    title: 'Israeli adolescents with ongoing exposure to terrorism: Suicidal ideation, posttraumatic stress disorder, and functional impairment',
    authors: ['Chemtob, C.', 'Pat-Horenczyk, R.', 'Madan, A.', 'Pitman, S.R.', 'Wang, Y.', 'Doppelt, O.', 'Dugan Burns, K.', 'Abramovitz, R.', 'Brom, D.'],
    journal: 'Journal of Traumatic Stress',
    year: 2011,
    details: '24(6), 756-759',
    type: 'article',
    topic: 'adolescents',
    sourceUrl: PAST,
  },
  {
    title: 'The influence of war and terrorism on posttraumatic distress among Israeli children',
    authors: ['Brom, D.', 'Pat-Horenczyk, R.', 'Baum, N.L.'],
    journal: 'International Psychiatry',
    year: 2011,
    details: '8(4), 81-83',
    type: 'article',
    topic: 'children-family',
    sourceUrl: PAST,
  },
  {
    title: `Are community studies of psychological trauma's impact accurate? A study among Jews and Palestinians`,
    authors: ['Hobfoll, S. E.', 'Canetti, D.', 'Hall, B. J.', 'Brom, D.', 'Palmieri, P. A.', 'Johnson, R. J.', 'Pat-Horenczyk, R.', 'Galea, S.'],
    journal: 'Psychological Assessment',
    year: 2011,
    details: '23(3), 599-605',
    type: 'article',
    topic: 'terror-war',
    sourceUrl: PAST,
  },
  {
    title: 'Coping flexibility and potential trauma: The perceived ability to cope with trauma (PACT) scale',
    authors: ['Bonanno, G.A.', 'Pat-Horenczyk, R.', 'Noll, J.'],
    journal: 'Psychological Trauma: Theory, Research, Practice and Policy',
    year: 2011,
    details: '3(2), 117-129',
    type: 'article',
    topic: 'other',
    sourceUrl: PAST,
  },
  {
    title: 'Seeking help: Do adolescents know when they need help? Jewish and Arab youths report on their posttraumatic distress in the aftermath of war',
    authors: ['Schiff, M.', 'Pat-Horenczyk, R.', 'Benbenishty, R.', 'Brom, D.', 'Baum, N.', 'Astor, R.A.'],
    journal: 'Journal of Traumatic Stress',
    year: 2010,
    details: '23(5), 657-660',
    type: 'article',
    topic: 'adolescents',
    sourceUrl: PAST,
  },
  {
    title: 'The role of social support for Israeli adolescents continually exposed to terrorism: Protective or compensatory factors?',
    authors: ['Schiff, M.', 'Pat-Horenczyk, R.', 'Peled, O.'],
    journal: 'Journal of Child & Adolescent Trauma',
    year: 2010,
    details: '3(2), 95-108',
    type: 'article',
    topic: 'adolescents',
    sourceUrl: PAST,
  },
  {
    title: 'Review of the international conference on trauma in early childhood',
    authors: ['Pat-Horenczyk, R.', 'Gill, R.'],
    journal: 'Psychoactualia',
    year: 2009,
    details: 'October, 25-29',
    language: 'he',
    type: 'article',
    topic: 'children-family',
    sourceUrl: PAST,
  },
  {
    title: 'Posttraumatic symptoms, functional impairment and coping among adolescents on both sides of the Israeli-Palestinian conflict: A cross-cultural approach',
    authors: ['Pat-Horenczyk, R.', 'Qasrawi, R.', 'Lesack, R.', 'Haj-Yahia, M. M.', 'Peled, O.', 'Shaheen, M.', 'Berger, R.', 'Brom, D.', 'Garber, R.', 'Abdeen, Z.'],
    journal: 'Applied Psychology: An International Review',
    year: 2009,
    details: '58(4), 688-708',
    type: 'article',
    topic: 'adolescents',
    sourceUrl: PAST,
  },
  {
    title: 'Building resilience in schools in the wake of Hurricane Katrina',
    authors: ['Baum, N.', 'Reidler, E.', 'Rotter, B.', 'Brom, D.'],
    journal: 'Journal of Child and Adolescent Trauma',
    year: 2009,
    details: '2(1)',
    type: 'article',
    topic: 'schools-resilience',
    sourceUrl: PAST,
  },
  {
    title: 'Building resilience for holocaust educators',
    authors: ['Baum, N.', 'Rotter, B.', 'Reidler, E.'],
    journal: 'Prism',
    year: 2009,
    details: '1:1, 81-88',
    type: 'article',
    topic: 'schools-resilience',
    sourceUrl: PAST,
  },
  {
    title: `School-based intervention for the prevention and treatment of elementary students' terror-related distress in Israel: A randomized control trial`,
    authors: ['Berger, R.', 'Pat-Horenczyk, R.', 'Gelkopf, M.'],
    journal: 'Journal of Traumatic Stress',
    year: 2007,
    details: '20(4), 541-551',
    type: 'article',
    topic: 'schools-resilience',
    sourceUrl: PAST,
  },
  {
    title: 'Israel kindergarten teachers cope with terror and war: Two implicit models of resilience',
    authors: ['Brody, D.', 'Baum, N.'],
    journal: 'Curriculum Inquiry',
    year: 2007,
    details: '37, 9-33',
    type: 'article',
    topic: 'schools-resilience',
    sourceUrl: PAST,
  },
  {
    title: 'The multiple faces of post traumatic growth',
    authors: ['Pat-Horenczyk, R.', 'Brom, D.'],
    journal: 'Applied Psychology: An International Review',
    year: 2007,
    details: '56(3), 379-385',
    type: 'article',
    topic: 'growth',
    sourceUrl: PAST,
  },
  {
    title: 'Adolescent exposure to recurrent terrorism in Israel: posttraumatic distress and functional impairment',
    authors: ['Pat-Horenczyk, R.', 'Abramovitz, R.', 'Peled, O.', 'Brom, D.', 'Daie, A.', 'Chemtob, C.M.'],
    journal: 'Journal of Orthopsychiatry',
    year: 2007,
    details: '77(1), 76-85',
    type: 'article',
    topic: 'adolescents',
    sourceUrl: PAST,
  },
  {
    title: 'Risk-taking behaviors among Israeli adolescents exposed to recurrent terrorism',
    authors: ['Pat-Horenczyk, R.', 'Peled, O.', 'Miron, T.', 'Villa, Y.', 'Brom, D.', 'Chemtob, C.M.'],
    journal: 'American Journal of Psychiatry',
    year: 2007,
    details: '164(1), 66-72',
    type: 'article',
    topic: 'adolescents',
    sourceUrl: PAST,
  },
  {
    title: 'Direct terrorism exposure, TV exposure to terrorism, and exposure to non-terrorism trauma and their differential associations with emotional and behavioral problems in young children',
    authors: ['Wang, Y.', 'Nomura, Y.', 'Pat-Horenczyk, R.', 'Doppelt, O.', 'Abramovitz, R.', 'Brom, D.', 'Chemtob, M.C.'],
    journal: 'Annals of New York Academy of Sciences',
    year: 2006,
    details: '1094, 363-368',
    type: 'article',
    topic: 'children-family',
    sourceUrl: PAST,
  },
  {
    title: 'Maintaining routine despite ongoing exposure to terrorism: A healthy strategy for adolescents?',
    authors: ['Pat-Horenczyk, R.', 'Schiff, M.', 'Doppelt, O.'],
    journal: 'Journal of Adolescent Health',
    year: 2006,
    details: '39(2), 199-205',
    type: 'article',
    topic: 'adolescents',
    sourceUrl: PAST,
  },
  {
    title: 'Post-traumatic distress in adolescents exposed to ongoing terror: Findings from a school-based screening project in the Jerusalem Area',
    authors: ['Pat-Horenczyk, R.'],
    journal: 'Journal of Aggression, Maltreatment and Trauma',
    year: 2004,
    details: '9 (No. 3/4). Co-published as a chapter in: The Trauma of Terrorism: Sharing Knowledge and Shared Care, An International Handbook (Haworth Press, 2005), pp. 335-347',
    type: 'article',
    topic: 'adolescents',
    sourceUrl: PAST,
  },
  {
    title: 'Tomorrow it could be me: Terror in Jerusalem',
    authors: ['Pat-Horenczyk, R.'],
    journal: 'Panim, A Quarterly for Society, Culture and Education',
    year: 2004,
    details: '28, 79-85',
    type: 'article',
    topic: 'terror-war',
    sourceUrl: PAST,
  },
  {
    title: 'On the second bi-national conference on treating traumatized children',
    authors: ['Pat-Horenczyk, R.'],
    journal: 'Psycho-actualia: A Quarterly of the Israeli Psychological Association',
    year: 2004,
    details: 'July, 14-17',
    type: 'article',
    topic: 'children-family',
    sourceUrl: PAST,
  },

  // ── Chapters ──
  {
    title: 'The impact of exposure to violence on aggression in children and adolescents: What can be learned from the trauma and resilience perspective',
    authors: ['Pat-Horenczyk, R.', 'Yeh, V.', 'Cohen, S.', 'Schramm, S.'],
    journal: 'Helping Children Cope with Trauma: Individual, Family and Community Perspectives (Routledge)',
    year: 2013,
    details: 'listed as in press, expected in 2013',
    type: 'chapter',
    topic: 'children-family',
    sourceUrl: PAST,
  },
  {
    title: 'Childhood bereavement and traumatic loss',
    authors: ['Baum, N. L.', 'Ginat, R.', 'Silverman, P.'],
    journal: 'Helping Children Cope with Trauma: Individual, Family and Community Perspectives',
    year: 2013,
    details: 'listed as in press, expected in 2013',
    type: 'chapter',
    topic: 'children-family',
    sourceUrl: PAST,
  },
  {
    title: 'Systems of care for traumatized children: The example of a School-based Intervention model',
    authors: ['Brom, D.', 'Baum, N.L.', 'Pat-Horenczyk, R.'],
    journal: 'Future Directions in PTSD: Diagnosis, Prevention, and Treatment (Springer)',
    details: 'listed as in press',
    type: 'chapter',
    topic: 'schools-resilience',
    sourceUrl: PAST,
  },
  {
    title: 'Ethical considerations in the treatment of post-traumatic distress',
    authors: ['Brom, D.', 'Pat-Horenczyk, R.'],
    journal: 'Handbook of Post-Traumatic Stress Disorders (De Tijdstroom, in Dutch)',
    year: 2012,
    details: 'pp. 737-752',
    type: 'chapter',
    topic: 'treatment',
    sourceUrl: PAST,
  },
  {
    title: 'The Influence of the Second Lebanese War on Israeli Students in Urban School Settings: Findings of the Nahariya District-Wide Screening Prototype',
    authors: ['Astor, R. A.', 'Benbenishty, R.', 'Pat-Horenczyk, R.', 'Brom, D.', 'Baum, N.', 'Schiff, M.', 'De Pedro, K.'],
    journal: 'International handbook of research in urban education (Taylor & Francis)',
    year: 2012,
    type: 'chapter',
    topic: 'schools-resilience',
    sourceUrl: PAST,
  },
  {
    title: 'Youth, Violence and Immigration: The Trauma Perspective',
    authors: ['Pat-Horenczyk, R.', 'Khodabakhsh, A.', 'van Heemstra, J.', 'Brom, D.'],
    journal: 'Perspectives on immigration and terrorism (NATO Emerging Security Challenges Division)',
    year: 2011,
    details: 'pp. 42-50',
    type: 'chapter',
    topic: 'adolescents',
    sourceUrl: PAST,
  },
  {
    title: 'A city-wide school-based model for addressing the needs of children exposed to terrorism and war',
    authors: ['Pat-Horenczyk, R.', 'Brom, D.', 'Baum, N.', 'Benbenishty, R.', 'Schiff, M.', 'Astor, R. A.'],
    journal: 'Post-traumatic syndromes in children and adolescents (Wiley/Blackwell)',
    year: 2011,
    type: 'chapter',
    topic: 'schools-resilience',
    sourceUrl: PAST,
  },
  {
    title: 'The search for risk and protective factors in childhood PTSD: From variables to processes',
    authors: ['Pat-Horenczyk, R.', 'Rabinowitz, R.', 'Rice, A.', 'Tucker-Levin, A.'],
    journal: 'Treating Traumatized Children: Risk, Resilience and Recovery (Routledge)',
    year: 2009,
    details: 'pp. 51-71',
    type: 'chapter',
    topic: 'children-family',
    sourceUrl: PAST,
  },
  {
    title: 'Toward a developing science and practice of childhood traumatic stress: Concluding comments',
    authors: ['Pat-Horenczyk, R.', 'Ford, J.', 'Brom, D.'],
    journal: 'Treating Traumatized Children: Risk, Resilience and Recovery (Routledge)',
    year: 2009,
    details: 'pp. 269-276',
    type: 'chapter',
    topic: 'children-family',
    sourceUrl: PAST,
  },
  {
    title: 'Entry on: Child Development',
    authors: ['Pat-Horenczyk, R.'],
    journal: 'Encyclopedia of Psychological Trauma (Wiley & Sons)',
    year: 2008,
    details: 'pp. 112-119',
    type: 'chapter',
    topic: 'children-family',
    sourceUrl: PAST,
  },
  {
    title: 'Terror in Jerusalem: Coping with "Emergency Routine" in Daily Life for adolescents, adults and helpers',
    authors: ['Pat-Horenczyk, R.'],
    journal: 'Terror in the Promised Land: Inside the Anguish of the Israeli-Palestinian Conflict (Praeger Press)',
    year: 2006,
    type: 'chapter',
    topic: 'terror-war',
    sourceUrl: PAST,
  },
  {
    title: 'Guidelines for early interventions for acute trauma in children and adolescents',
    authors: ['Rachamin, L.', 'Gilboa-Shechtman, E.', 'Ben-Moshe, R.', 'Pat-Horenczyk, R.', 'Galili-Weistub, E.', 'Benharash, F.', 'Apter, A.'],
    journal: 'Early interventions after disasters and terrorism: The Israeli experience (Ramot, Tel-Aviv University Press)',
    year: 2005,
    details: 'pp. 303-333',
    language: 'he',
    type: 'chapter',
    topic: 'treatment',
    sourceUrl: PAST,
  },
  {
    title: 'Screening posttraumatic distress among Israeli adolescents exposed to ongoing terrorism',
    authors: ['Pat-Horenczyk, R.', 'Doppelt, O.'],
    journal: `Mental health in terror's shadow: The Israeli experience (Ramot, Tel-Aviv University Press)`,
    year: 2005,
    details: 'pp. 55-76',
    language: 'he',
    type: 'chapter',
    topic: 'adolescents',
    sourceUrl: PAST,
  },
  {
    title: 'Building resilience in the preschool classroom: A psychoeducational response to exposure to terror',
    authors: ['Baum, N. L.'],
    journal: 'Israel Responds to Terrorism (Ramot)',
    year: 2005,
    language: 'he',
    type: 'chapter',
    topic: 'schools-resilience',
    sourceUrl: PAST,
  },
  {
    title: 'Building Resilience: A School Based Intervention for Children Exposed to ongoing Trauma and Stress',
    authors: ['Baum, N.'],
    journal: 'The Trauma of Terrorism: An International handbook of Shared Knowledge and Shared Care (Haworth Press)',
    year: 2004,
    type: 'chapter',
    topic: 'schools-resilience',
    sourceUrl: PAST,
  },
];
